name: Workflows

on:
  #push:
  #  branches-ignore:
  #    - '**'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3